### ISSUE TITLE
Manifest URL changed?

### ISSUE THREAD

**Issue by samueljero** [seL4/camkes-vm-apps#3]
Hello, the URL for the manifest currently specified in the README build instructions (https://github.com/SEL4PROJ/camkes-vm-manifest.git) appears to be dead (returning 404). It looks like it may have been moved to: https://github.com/seL4/camkes-vm-examples-manifest.git.

**Comment by axel-h** [comment]
I was assuming `SEL4PROJ` set up to redirect to `seL4`, is this no longer the case now because this was just temporary?

**Comment by samueljero** [comment]
There is no redirect in place for me. Possibly because I have no permissions on seL4 repos?

If I hit https://github.com/SEL4PROJ/camkes-vm-manifest in a web browser, I see a 404 page.

If I attempt to `git clone https://github.com/SEL4PROJ/camkes-vm-manifest.git`, I get asked for authentication, which is odd. My usual github credentials result in failed auth.

**Comment by lsf37** [comment]
Hm, the redirect used to work, and it's automatic, i.e. I didn't configure anything for it, but I can confirm that it is broken for me as well. Maybe they just expire after a certain amount of time.

This is a bit of a worry, because I was hoping that old manifests would keep working, but I'll update the README in any case.
